### PR TITLE
Jira 2

### PR DESCRIPTION
**Pull request by rajesh-jagtap**
I am doing practice.

### CODE REVIEW

**Comment by rajesh-jagtap** [comment]
Hello Arjun ! Please review my code.

**Review by arjun5-jagtap — CHANGES_REQUESTED** [review]
There is a requirement to improve the code.

**Review by rajesh-jagtap — COMMENTED** [review]
I did the desired changes.Now,please approve it.

**Review by arjun5-jagtap — APPROVED** [review]
It is approved now.

**Pull request merged**
